---
title: "Test_Usecase"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Test_Usecase}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mandrake)
library(drake)
library(knitr)
library(magrittr)

source("mtcars/R/functions.R")
```


```{r plan}
# This is where you set up your workflow plan,
# a data frame with the steps of your analysis.

my_plan <- drake::drake_plan(
  report = knit(knitr_in("mtcars/report.Rmd"), file_out("mtcars/report.md"), quiet = TRUE),
  small = simulate(48),
  large = simulate(64),
  regression1 = target(
    reg1(data),
    transform = map(data = c(small, large), .tag_out = reg, .tag_in = cluster_id)
  ),
  regression2 = target(
    reg2(data),
    transform = map(data, .tag_out = reg, .tag_in = cluster_id)
  ),
  summ = target(
    suppressWarnings(summary(reg$residuals)),
    transform = map(reg, .tag_in = cluster_id)
  ),
  coef = target(
    suppressWarnings(summary(reg))$coefficients,
    transform = map(reg, .tag_in = cluster_id)
  ),
  
  mtcars = target(
    mtcars
  ),
  
  mtcars_summary = target({
      out <- mtcars %>%
        dplyr::group_by(cyl) %>%
        dplyr::summarise(dplyr::across(c(disp, hp, drat, wt, qsec), mean))
      out    
    },
   desc = "
## Average of attributes of cars according to number of cylinders 
This dataframe relates `cyl` (number of cylinders) to a few properties of mtcars
"
  ),
  trace = TRUE
)
```

```{r, echo=FALSE}
my_plan %>% 
  dplyr::mutate(dplyr::across("command", rlang::as_label)) %>%
  knitr::kable("html") %>%
  kableExtra::kable_styling(c("striped", "responsive", "condensed"))
```

```{r}
cache <- drake::get_cache()
my_config <- drake_config(my_plan)
drake::make(config = my_config)

```

```{r}
lookup_cache <- mandrake::load_package_colspec("mandrake")
```

```{r}
plan_extracted <- my_plan %>%
  mandrake::decorate_plan(cache, group = "cluster_id", lookup_cache = lookup_cache)
```

```{r}
plan_extracted
```

```{r}
my_config <- drake_config(plan_extracted)
```

```{r}
graph_info <- drake_graph_info(
  my_config, 
  group = "cluster_id", 
  clusters = c("summ", "coef"), 
  build_times = "none",
  on_select_col = "target_column_list")

graph <- render_drake_graph(
  graph_info, 
  on_select = mandrake::embed_event_handler(),
  ncol_legend = 4
  ) 
```
```{r, echo=FALSE}
graph %<>%
  visNetwork::visHierarchicalLayout(
    direction = "LR", levelSeparation = 250
    ) %>%
  visNetwork::visEdges(
    smooth = list(type = "cubicBezier", forceDirection = "horizontal")
    )
```

# Graph
```{r}
graph
```
